name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - cicd

jobs:
  Install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

  Tests:
    runs-on: ubuntu-latest

    steps: # Ajouté une section "steps" pour définir les étapes
      - name: Running tests
        run: npm test

  Build:
    runs-on: ubuntu-latest

    steps: # Ajouté une section "steps" pour définir les étapes
      - name: Change directory
        run: cd .. # La commande "cd" est correcte, mais la syntaxe doit être "run: cd .."

      - name: Build project
        run: npm run build
