name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - cicd

jobs:
  Install:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: npm install
        working-directory: .

  Tests:
    needs: Install
    runs-on: ubuntu-latest

    steps:
      - name: Restore Node.js dependencies from cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}

      - name: Running tests
        run: npm test

  Build:
    needs: Install
    runs-on: ubuntu-latest

    steps:
      - name: Restore Node.js dependencies from cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}

      - name: Build project
        run: npm run build
